# Set the version of docker compose to use
version: '3.9'

# The containers that compose the project
services:
  db:
    image: mongo
    restart: always
    container_name: integration-tests-prisma
    # ports:
    #   - '5433:5432'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@integration-tests-prisma:27017
