export default [
  {
    id: Math.random(),
    imageUrl: '/images/products/snowshoes.jpeg',
    imageAlt: 'Entry level snowshoes',
    category: 'snow',
    stock: '3',
    rental_min: '2',
    title: 'Entry level snowshoes',
    brand: 'Black Diamond',
    price: 12,
    reviewCount: 34,
    rating: 4.7,
    description: 'Great for a relaxing day in powder',
  },
  {
    id: Math.random(),
    imageUrl: '/images/products/ski_boots.webp',
    imageAlt: 'Ski Boots',
    stock: '2',
    category: 'snow',
    rental_min: '2',
    title: 'Downhill ski boots',
    brand: 'Black Diamond',
    gender: 'w',
    size: 6,
    price: 25,
    reviewCount: 34,
    rating: 4.9,
    description: 'Great for a relaxing day in powder',
  },
  {
    id: Math.random(),
    imageUrl: '/images/products/ski_boots_men.jpeg',
    imageAlt: 'Ski Boots',
    stock: '2',
    category: 'snow',
    rental_min: '2',
    title: 'Downhill ski boots',
    brand: 'Black Diamond',
    gender: 'm',
    size: 11,
    price: 28,
    reviewCount: 34,
    rating: 4.9,
    description: 'Great for a relaxing day in powder',
  },
  {
    id: Math.random(),
    imageUrl: '/images/products/yeti_45.webp',
    imageAlt: 'Yeti Tundra 45',
    stock: '2',
    category: 'cooler',
    rental_min: '2',
    title: '45 liter Yeti cooler',
    brand: 'Yeti',
    price: 20,
    reviewCount: 34,
    rating: 5,
    description: 'Keeps the food and beer cold',
  },
  {
    id: Math.random(),
    imageUrl: '/images/products/yeti_65.webp',
    imageAlt: 'Yeti Tundra 65',
    stock: '2',
    category: 'cooler',
    rental_min: '2',
    title: '65 liter Yeti cooler',
    brand: 'Yeti',
    price: 28,
    reviewCount: 34,
    rating: 4.7,
    description: 'Keeps the food and beer cold',
  },
  {
    id: Math.random(),
    imageUrl: '/images/products/green_mountain_grill.jpeg',
    imageAlt: 'Green Mountain Grill Pellet Smoker',
    stock: '3',
    category: 'snow',
    rental_min: '2',
    title: 'Green Mountain Grill Pellet Smoker',
    brand: 'Green Mountain Grill',
    price: 50,
    reviewCount: 34,
    rating: 4.7,
    description: 'Great for an overnight brisket smoke',
  },
];
