export default [
  {
    imageUrl: "https://bit.ly/2Z4KKcF",
    imageAlt: "Entry level snowshoes",
    stock: '3',
    rental_min: '2',
    title: "Entry level snowshoes",
    formattedPrice: "$12.00",
    reviewCount: '34',
    rating: 4.7,
  },
  {
    imageUrl: "https://bit.ly/2Z4KKcF",
    imageAlt: "Entry level snowshoes",
    stock: '3',
    rental_min: '2',
    title: "Entry level snowshoes",
    formattedPrice: "$12.00",
    reviewCount: '34',
    rating: 4.7,
  },
  {
    imageUrl: "https://bit.ly/2Z4KKcF",
    imageAlt: "Entry level snowshoes",
    stock: '3',
    rental_min: '2',
    title: "Entry level snowshoes",
    formattedPrice: "$12.00",
    reviewCount: '34',
    rating: 4.7,
  },
];
